export const tags = [
  "Nightclub",
  "Café",
  "Speakeasy",
  "Rooftop",
  "Underground",
  "Karaoke",
  "Sports Bar",
  "Dive",
  "Cocktail Lounge",
  "Whiskey Bar",
  "Craft Beer",
  "Wine Bar",
  "Live Music",
  "Dance Floor",
  "Outdoor Seating",
  "Garden",
  "Art Deco",
  "Retro",
  "Themed",
  "Industrial",
  "LGBTQ+ Friendly",
  "Pet-Friendly",
  "Arcade",
  "Tiki",
  "Sushi & Sake",
  "Seafood Bar",
  "Private Rooms",
  "Fireplace",
  "Artisanal Cocktails",
  "Mocktails",
  "Historic Venue",
  "Jazz & Blues",
  "Patio",
  "BYOB",
  "Craft Distillery",
  "Accessible",
  "Accessibility bathrooms",
  "Gastropub",
  "Pub",
  "Garden",
  "Terrace",
  "Tequila",
  "Rum",
  "Wine",
  "Vodka",
  "Whiskey",
  "Gin",
  "Tapas",
  "Mediterranean",
  "Caribbean",
  "Latin",
  "Afro",
  "Asian",
  "Polynesian",
  "Greek",
  "Italian",
  "French",
  "Spanish",
  "Mexican",
  "German",
  "Irish",
  "Scottish",
  "Korean",
  "Japanese",
  "Chinese",
  "Scandinavian",
  "Middle Eastern",
  "Fusion",
  "Vegan",
  "Vegetarian",
  "Organic",
  "Farm-to-Table",
  "Fine Dining",
  "Casual Dining",
  "Family Friendly",
  "Romantic",
  "High-End",
  "Trendy",
  "Late Night",
  "Happy Hour",
  "Food Truck",
  "Self-Serve",
  "Outdoor Bar",
  "Roof Deck",
  "Brunch",
  "Breakfast",
  "Late-Night Eats",
  "Low-Key",
  "High Energy",
  "Music Lounge",
  "Dance Hall",
  "Cozy",
  "Minimalist",
  "Luxury",
  "Barbecue",
  "Bistro",
  "Pop-Up",
  "Seasonal",
  "Cocktail Classes",
  "Wine Tasting",
  "Distillery Tours",
  "Microbrewery",
  "Craft Cocktails",
  "Non-Alcoholic Options",
  "Board Games",
  "Trivia Nights",
  "Karaoke Nights",
  "Outdoor Fire Pits",
  "Food & Drink Pairing",
  "Locally Sourced",
  "Historical Building",
  "Seaside View",
  "Live DJ",
  "Silent Disco",
  "Whiskey Tasting",
  "Live Comedy",
  "Poetry Readings",
  "Film Screenings",
  "Rooftop Garden",
  "Tap Takeovers",
  "Champagne Bar",
  "Martini Lounge",
  "Poolside",
  "Brewpub",
  "Petite Plates",
  "Sunset Views",
  "Vegan-Friendly",
  "Farmhouse Style",
  "Cocktail Flights",
  "Retro Arcade",
  "Community Events",
  "Open Mic",
  "Sports Viewing",
  "Speakeasy Vibes",
  "Supper Club",
  "Underwater Theme",
  "Garden Patio",
  "Taproom",
  "Wine Cellar",
  "Martini Bar",
  "Craft Spirits",
  "Neon Lighting",
  "Mystical Vibes",
  "Beachside",
  "Ski Lodge",
  "Winery",
  "Rock Climbing Wall",
  "Experimental Cocktails",
  "Mixology Workshops",
  "Smooth Jazz",
  "Big Band Swing",
  "Roaring Twenties",
  "Neo-Vintage",
  "Botanical Garden",
  "Pirate Theme",
  "Speakeasy Hidden Entrance",
  "Dim Sum",
  "Southern Comfort Food",
  "Cajun & Creole",
  "Brazilian BBQ",
  "Dance Classes",
  "Retro Diner",
  "Game Night",
  "Fine Wine Selection",
  "Single Malt Whiskeys",
  "Mixologist Specials",
  "Eco-Friendly",
  "Plant-Based Menu",
  "Street Food",
  "Authentic Experience",
  "Virtual Reality Games",
  "Trivia Competitions",
  "Ramen & Sake",
  "Street Art Vibes",
  "Creative Cocktails",
  "Absinthe Bar",
  "Apothecary Theme",
  "Speakeasy Jazz",
  "Neon Jungle",
  "Art Gallery",
  "Wilderness Retreat",
  "Forest Hideaway",
  "Outdoor Cinema",
  "Outdoor Adventures",
  "Vegan BBQ",
  "Wine & Cheese Pairing",
  "Bourbon Tastings",
  "Oyster Bar",
  "Wine Cellar Tours",
  "Hot Chocolate Bar",
  "Piano Lounge",
  "Luxury Suite",
  "Craft Ice Cream",
  "Holiday Theme",
  "Cocktail Lab",
  "Private Chef",
  "Gastro Lounge",
  "VIP Lounge",
  "Virtual Mixology",
  "Carnival Theme",
  "Retro Cabaret",
  "Burlesque Shows",
  "Secret Passageways",
  "Lava Rock Grill",
  "Forest Setting",
  "Handcrafted Decor",
  "Beach Cabana",
  "Alpine Chalet",
  "Country Style",
  "Desert Oasis",
  "Oceanfront",
  "Waterfall View",
  "Mountain View",
  "Urban Rooftop",
  "Modernist",
  "Hidden Gem",
  "Moonlit Patio",
  "Rooftop Pool",
  "International Cuisine",
  "Snow Lounge",
  "Cigar Lounge",
  "Experimental Cuisine",
  "Immersive Decor",
  "Luxury Beachfront",
  "Vintage Cars",
  "Art Installations",
  "Glasshouse",
  "Winter Wonderland",
  "Igloo Bar",
  "Fire and Ice Theme",
  "Ice Sculptures",
  "Puppy Meetups",
  "Live Flamenco",
  "Wine & Whiskey Flights",
  "Gin Distillery",
  "Chef's Table",
  "Space Age Theme",
  "80's Retro Vibe",
  "Silent Movies",
  "Cliffside",
  "Mezcal Bar",
  "Ocean-Inspired Decor",
  "Indie Vibes",
  "Street Vibes"
] as const;

export type Tag = typeof tags[number]
